/**
 * CopilotPage — SENTINAL AI Security Co-Pilot
 *
 * A chat interface grounded in real AttackEvent data from MongoDB.
 * Every answer is generated by Gemini 1.5 Flash with live attack context
 * injected into the prompt — not a generic chatbot.
 *
 * Features:
 *   - Multi-turn message history (client-side, in-memory)
 *   - Suggested starter questions tailored to security analysts
 *   - Context indicator showing how many attacks informed the answer
 *   - Graceful degradation when GEMINI_API_KEY is not set
 */
import React, { useState, useRef, useEffect, useCallback } from 'react';
import PageWrapper  from '../components/layout/PageWrapper';
import Panel        from '../components/ui/Panel';
import { geminiChat } from '../services/api';

// ── Icons ─────────────────────────────────────────────────────────────────────
const IconSend = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <line x1="22" y1="2" x2="11" y2="13" />
    <polygon points="22 2 15 22 11 13 2 9 22 2" />
  </svg>
);

const IconBot = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
    <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    <line x1="12" y1="3" x2="12" y2="7" />
    <circle cx="9" cy="16" r="1" fill="currentColor" />
    <circle cx="15" cy="16" r="1" fill="currentColor" />
  </svg>
);

const IconUser = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
    <circle cx="12" cy="7" r="4" />
  </svg>
);

const IconSpinner = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
    style={{ animation: 'spin 1s linear infinite' }}>
    <path d="M21 12a9 9 0 1 1-6.219-8.56" />
  </svg>
);

const IconClear = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <polyline points="3 6 5 6 21 6" />
    <path d="M19 6l-1 14H6L5 6" />
    <path d="M10 11v6" /><path d="M14 11v6" />
    <path d="M9 6V4h6v2" />
  </svg>
);

// ── Suggested starter questions ───────────────────────────────────────────────
const SUGGESTIONS = [
  'What are the top 3 attack types in the last 24 hours?',
  'Which IP address is the most aggressive attacker?',
  'How many critical attacks were not blocked?',
  'What SQL injection payloads have been detected?',
  'Which attacks have the highest confidence scores?',
  'Are there any signs of a coordinated attack campaign?',
];

// ── Message bubble component ──────────────────────────────────────────────────
function MessageBubble({ msg }) {
  const isUser = msg.role === 'user';
  return (
    <div style={{
      display: 'flex',
      flexDirection: isUser ? 'row-reverse' : 'row',
      alignItems: 'flex-start',
      gap: 'var(--space-3)',
      marginBottom: 'var(--space-4)',
    }}>
      {/* Avatar */}
      <div style={{
        width: 30,
        height: 30,
        borderRadius: 'var(--radius-full)',
        background: isUser ? 'var(--color-accent)' : 'var(--color-surface-3)',
        border: '1px solid var(--color-border)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
        color: isUser ? 'var(--color-bg)' : 'var(--color-accent)',
      }}>
        {isUser ? <IconUser /> : <IconBot />}
      </div>

      {/* Bubble */}
      <div style={{
        maxWidth: '78%',
        background: isUser ? 'var(--color-accent)' : 'var(--color-surface-2)',
        color: isUser ? 'var(--color-bg)' : 'var(--color-text)',
        border: isUser ? 'none' : '1px solid var(--color-border)',
        borderRadius: isUser
          ? 'var(--radius-lg) var(--radius-sm) var(--radius-lg) var(--radius-lg)'
          : 'var(--radius-sm) var(--radius-lg) var(--radius-lg) var(--radius-lg)',
        padding: 'var(--space-3) var(--space-4)',
        fontSize: 'var(--text-sm)',
        lineHeight: 1.6,
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-word',
      }}>
        {msg.content}
        {msg.context_attacks != null && (
          <div style={{
            marginTop: 'var(--space-2)',
            fontSize: 'var(--text-xs)',
            opacity: 0.65,
            fontStyle: 'italic',
          }}>
            Grounded in {msg.context_attacks} recent attacks
          </div>
        )}
      </div>
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────
export default function CopilotPage() {
  const [messages,  setMessages]  = useState([]);
  const [input,     setInput]     = useState('');
  const [loading,   setLoading]   = useState(false);
  const [error,     setError]     = useState(null);
  const bottomRef   = useRef(null);
  const inputRef    = useRef(null);

  // Scroll to bottom whenever messages change
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const handleSend = useCallback(async (question) => {
    const q = (question ?? input).trim();
    if (!q || loading) return;

    setInput('');
    setError(null);
    setMessages(prev => [...prev, { role: 'user', content: q }]);
    setLoading(true);

    try {
      const data = await geminiChat(q);
      setMessages(prev => [...prev, {
        role: 'assistant',
        content: data.answer,
        context_attacks: data.context_attacks,
      }]);
    } catch (err) {
      const msg = err?.response?.data?.message || err.message || 'Request failed';
      setError(msg);
      setMessages(prev => [...prev, {
        role: 'assistant',
        content: `Error: ${msg}`,
      }]);
    } finally {
      setLoading(false);
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [input, loading]);

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const clearChat = () => {
    setMessages([]);
    setError(null);
    setInput('');
    setTimeout(() => inputRef.current?.focus(), 50);
  };

  const isEmpty = messages.length === 0;

  return (
    <PageWrapper>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      <div className="page-container" style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>

        {/* Page Header */}
        <div className="page-header" style={{ marginBottom: 'var(--space-4)' }}>
          <div className="page-title-group">
            <h1 className="page-title" style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
              <span style={{ color: 'var(--color-accent)' }}><IconBot /></span>
              AI Security Co-Pilot
            </h1>
            <p className="page-subtitle">
              Ask questions about your live attack data. Every answer is grounded in real MongoDB telemetry.
            </p>
          </div>
          {messages.length > 0 && (
            <div className="page-actions">
              <button className="btn btn-ghost btn-sm" onClick={clearChat}
                style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-1)' }}>
                <IconClear /> Clear
              </button>
            </div>
          )}
        </div>

        {/* Chat panel */}
        <Panel style={{ flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 }}>

          {/* Message area */}
          <div style={{
            flex: 1,
            overflowY: 'auto',
            padding: 'var(--space-4)',
            minHeight: 0,
          }}>
            {/* Empty state with suggestions */}
            {isEmpty && (
              <div style={{ textAlign: 'center', padding: 'var(--space-8) var(--space-4)' }}>
                <div style={{
                  width: 56,
                  height: 56,
                  borderRadius: 'var(--radius-full)',
                  background: 'var(--color-surface-2)',
                  border: '1px solid var(--color-border)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  margin: '0 auto var(--space-4)',
                  color: 'var(--color-accent)',
                }}>
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <rect x="3" y="11" width="18" height="11" rx="2" />
                    <path d="M7 11V7a5 5 0 0 1 10 0v4" />
                    <line x1="12" y1="3" x2="12" y2="7" />
                    <circle cx="9" cy="16" r="1" fill="currentColor" />
                    <circle cx="15" cy="16" r="1" fill="currentColor" />
                  </svg>
                </div>
                <p style={{ color: 'var(--color-text)', fontWeight: 'var(--weight-semibold)', marginBottom: 'var(--space-1)' }}>
                  SENTINEL AI is ready
                </p>
                <p style={{ color: 'var(--color-text-muted)', fontSize: 'var(--text-sm)', marginBottom: 'var(--space-6)' }}>
                  Ask anything about your live attack telemetry
                </p>
                <div style={{
                  display: 'flex',
                  flexWrap: 'wrap',
                  gap: 'var(--space-2)',
                  justifyContent: 'center',
                  maxWidth: 600,
                  margin: '0 auto',
                }}>
                  {SUGGESTIONS.map(s => (
                    <button
                      key={s}
                      onClick={() => handleSend(s)}
                      style={{
                        background: 'var(--color-surface-2)',
                        border: '1px solid var(--color-border)',
                        borderRadius: 'var(--radius-full)',
                        padding: 'var(--space-2) var(--space-3)',
                        fontSize: 'var(--text-xs)',
                        color: 'var(--color-text-muted)',
                        cursor: 'pointer',
                        transition: 'all 0.15s ease',
                        textAlign: 'left',
                      }}
                      onMouseEnter={e => {
                        e.currentTarget.style.borderColor = 'var(--color-accent)';
                        e.currentTarget.style.color = 'var(--color-accent)';
                      }}
                      onMouseLeave={e => {
                        e.currentTarget.style.borderColor = 'var(--color-border)';
                        e.currentTarget.style.color = 'var(--color-text-muted)';
                      }}
                    >
                      {s}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Messages */}
            {messages.map((msg, i) => <MessageBubble key={i} msg={msg} />)}

            {/* Loading indicator */}
            {loading && (
              <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)',
                color: 'var(--color-text-muted)', fontSize: 'var(--text-sm)',
                marginBottom: 'var(--space-4)' }}>
                <div style={{
                  width: 30, height: 30,
                  borderRadius: 'var(--radius-full)',
                  background: 'var(--color-surface-3)',
                  border: '1px solid var(--color-border)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  color: 'var(--color-accent)', flexShrink: 0,
                }}>
                  <IconBot />
                </div>
                <span style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-1)' }}>
                  <IconSpinner /> Analyzing attack data...
                </span>
              </div>
            )}

            <div ref={bottomRef} />
          </div>

          {/* Divider */}
          <div style={{ borderTop: '1px solid var(--color-border)' }} />

          {/* Input area */}
          <div style={{ padding: 'var(--space-3) var(--space-4)' }}>
            {error && (
              <p style={{ fontSize: 'var(--text-xs)', color: 'var(--color-critical)',
                marginBottom: 'var(--space-2)' }}>{error}</p>
            )}
            <div style={{ display: 'flex', gap: 'var(--space-2)', alignItems: 'flex-end' }}>
              <textarea
                ref={inputRef}
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Ask about your attack data... (Enter to send)"
                rows={2}
                disabled={loading}
                style={{
                  flex: 1,
                  resize: 'none',
                  background: 'var(--color-surface-2)',
                  border: '1px solid var(--color-border)',
                  borderRadius: 'var(--radius-md)',
                  padding: 'var(--space-2) var(--space-3)',
                  fontSize: 'var(--text-sm)',
                  color: 'var(--color-text)',
                  fontFamily: 'var(--font-body)',
                  outline: 'none',
                  transition: 'border-color 0.15s',
                }}
                onFocus={e => e.target.style.borderColor = 'var(--color-accent)'}
                onBlur={e  => e.target.style.borderColor = 'var(--color-border)'}
              />
              <button
                onClick={() => handleSend()}
                disabled={loading || !input.trim()}
                className="btn btn-primary"
                style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-1)',
                  paddingBlock: 'var(--space-3)' }}
              >
                {loading ? <IconSpinner /> : <IconSend />}
                {loading ? 'Thinking…' : 'Send'}
              </button>
            </div>
            <p style={{ fontSize: 'var(--text-xs)', color: 'var(--color-text-muted)',
              marginTop: 'var(--space-1)' }}>
              Shift+Enter for new line · answers grounded in live MongoDB attack telemetry
            </p>
          </div>
        </Panel>
      </div>
    </PageWrapper>
  );
}
